---
title: "concatenate_files"
author: "Savannah McNair"
date: "2025-01-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

necessary packages
```{r}
library(dplyr)
```

Load in your paths
directory path is where you have saved your summary stats or trial measures data
output path is where you would like the outputs to get saved
```{r}
#SM set to the location you downloaded the EEG files to. If you are using a Windows computer, you will need to change the direction of the slashes from '\' to '/'
directory_path <- "X:/Projects/hbcd/EEG/Main_Study/CBRAIN_8.14/"
output_path <- "Z:/Dropboxes/tmahesh/data release csvs/"
```


set cwd to file path, get ids 
```{r}
setwd(directory_path) 
cwd <- directory_path
dccids <- list.files()
```

create sheets
```{r}
RS_power <- NULL
FACE_SME <- NULL
FACE_trial <- NULL
MMN_SME <- NULL
MMN_trial <- NULL
VEP_trial <- NULL
VEP_SME <- NULL
```

for each folder (ID), pull summary stats by task and condition
#change names of files to new names!!!
```{r}
for (x in dccids) {
  processed_data <- paste(x, "/ses-V03/eeg/processed_data", sep="")
  
  RS_power_file <- paste(cwd, processed_data, "/", x, "_ses-V03_task-RS_Power-summaryStats.csv", sep="")
  if (file.exists(RS_power_file)) {
    RS_power_sheet <- read.csv(RS_power_file)
    for (i in 1:nrow(RS_power_sheet)) {
      row <- RS_power_sheet[i, , drop = FALSE]
      RS_power <- rbind(RS_power, row)
    }
  } else {
    message(paste("RS Power file not found for", x))
  }
  
  FACE_summary_file <- paste(cwd, processed_data, "/", x, "_ses-V03_task-FACE_ERP-summaryStats.csv", sep="")
  if (file.exists(FACE_summary_file)) {
    FACE_summary_sheet <- read.csv(FACE_summary_file)
    for (i in 1:nrow(FACE_summary_sheet)) {
      FACE_summary_sheet$ID <- x
      row <- FACE_summary_sheet[i, , drop = FALSE]
      FACE_SME <- rbind(FACE_SME, row)
    }
  } else {
    message(paste("FACE file not found for", x))
  }
  
  MMN_summary_file <- paste(cwd, processed_data, "/", x, "_ses-V03_task-MMN_ERP-summaryStats.csv", sep="")
  if (file.exists(MMN_summary_file)) {
    MMN_summary_sheet <- read.csv(MMN_summary_file)
    for (i in 1:nrow(MMN_summary_sheet)) {
      MMN_summary_sheet$ID <- x
      row <- MMN_summary_sheet[i, , drop = FALSE]
      MMN_SME <- rbind(MMN_SME, row)
    }
  } else {
    message(paste("MMN file not found for", x))
  }
  
  VEP_summary_file <- paste(cwd, processed_data, "/", x, "_ses-V03_task-VEP_ERP-summaryStats.csv", sep="")
  if (file.exists(VEP_summary_file)) {
    VEP_summary_sheet <- read.csv(VEP_summary_file)
    for (i in 1:nrow(VEP_summary_sheet)) {
      VEP_summary_sheet$ID <- x
      row <- VEP_summary_sheet[i, , drop = FALSE]
      VEP_SME <- rbind(VEP_SME, row)
    }
  } else {
    message(paste("VEP file not found for", x))
  }
}

```


output df as a csv
```{r}
write.csv(FACE_SME, paste(output_path, "FACE_SME.csv", sep="")) #SM change these names to where you would like to output the summary sheets, keeping the "{TASK}_SME.csv"
write.csv(RS_power,paste(output_path,"RS_power.csv", sep=""))
write.csv(MMN_SME,paste(output_path, "MMN_SME.csv", sep = ""))
write.csv(VEP_SME,paste(output_path, "VEP_SME.csv", sep = ""))
```

