---
title: "Get_Mean_Amp"
author: "Trisha Maheshwari"
date: "2025-01-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load in your paths
directory path is where you have saved your summary stats or trial measures data
output path is where you would like the outputs to get saved
```{r}
#SM set to the location you downloaded the EEG files to. If you are using a Windows computer, you will need to change the direction of the slashes from '\' to '/'
directory_path <- "Z:/Dropboxes/tmahesh/testing made outputs/"
output_path <- "Z:/Dropboxes/tmahesh/data release csvs/"
```


set cwd to file path, get ids 
```{r}
setwd(directory_path) 
cwd <- directory_path
dccids <- list.files()
```

for each folder (ID), pull trial measures and summary stats
create a mean score from trial measures per condition, and add that mean score to summary stats
```{r}
for (x in dccids) {
  processed_data <- paste(x, "/ses-V03/eeg/processed_data", sep="")
  
  VEP_trial <- paste(cwd, processed_data, "/", x, "_ses-V03_task-VEP_ERPTrialMeasures.csv", sep="")
  VEP_sum <- paste(cwd, processed_data, "/", x, "_ses-V03_task-VEP_ERPSummaryStats.csv", sep="")
  if (file.exists(VEP_trial) & file.exists(VEP_sum)) {
    VEP_trial_sheet <- read.csv(VEP_trial)
    VEP_summary_sheet <- read.csv(VEP_sum)
    cols <- grepl("MeanAmplitude", names(VEP_trial_sheet))
    VEP_Amps <- VEP_trial_sheet[,cols] #list of just amp columns
    newcols <- colnames(VEP_Amps)
    VEP_summary_sheet[c(newcols)] <- NA
    
    for (i in 1:ncol(VEP_Amps)) {
      meanamp = mean(VEP_Amps[,i])
      VEP_summary_sheet[,colnames(VEP_Amps)[i]] = meanamp
    }
  } else {
    message(paste("VEP file not found for", x))
  }
  
  FACE_trial <- paste(cwd, processed_data, "/", x, "_ses-V03_task-FACE_ERPTrialMeasures.csv", sep="")
  FACE_sum <- paste(cwd, processed_data, "/", x, "_ses-V03_task-FACE_ERPSummaryStats.csv", sep="")
  if (file.exists(FACE_trial) & file.exists(FACE_sum)) {
    FACE_trial_sheet <- read.csv(FACE_trial)
    FACE_summary_sheet <- read.csv(FACE_sum)
    cols <- grepl("MeanAmplitude", names(FACE_trial_sheet))
    #FACE_Amps <- FACE_trial_sheet[,cols] #list of just amp columns
    newcols <- colnames(FACE_trial_sheet[,cols])
    FACE_summary_sheet[c(newcols)] <- NA

    #sep out by condition
    FACE_uprightInv = subset(FACE_trial_sheet, Condition == "uprightInv")
    FACE_uprightInv <- FACE_uprightInv[,cols] #list of just amp columns
    FACE_uprightObj = subset(FACE_trial_sheet, Condition == "uprightObj")
    FACE_uprightObj <- FACE_uprightObj[,cols] #list of just amp columns
    FACE_object = subset(FACE_trial_sheet, Condition == "object")
    FACE_object <- FACE_object[,cols] #list of just amp columns
    FACE_inverted = subset(FACE_trial_sheet, Condition == "inverted")
    FACE_inverted <- FACE_inverted[,cols] #list of just amp columns
    amp_sheets <- c(FACE_uprightInv, FACE_uprightObj, FACE_object, FACE_inverted)
    
    for (i in 1:ncol(FACE_uprightInv)){
      #basically go through each condition (4) and find mean amp for each column (4) and add it to the corresponding row in summary sheet
      meanamp = mean(FACE_uprightInv[,i])
      FACE_summary_sheet[FACE_summary_sheet$Condition == "uprightInv",colnames(FACE_uprightInv)[i]] = meanamp 
      meanamp = mean(FACE_uprightObj[,i])
      FACE_summary_sheet[FACE_summary_sheet$Condition == "uprightObj",colnames(FACE_uprightObj)[i]] = meanamp 
      meanamp = mean(FACE_object[,i])
      FACE_summary_sheet[FACE_summary_sheet$Condition == "object",colnames(FACE_object)[i]] = meanamp 
      meanamp = mean(FACE_inverted[,i])
      FACE_summary_sheet[FACE_summary_sheet$Condition == "inverted",colnames(FACE_inverted)[i]] = meanamp 
    }
  } else {
    message(paste("FACE file not found for", x))
  }
  
  # 
  # MMN_summary_file <- paste(cwd, processed_data, "/", x, "_ses-V03_task-MMN_ERP-summaryStats.csv", sep="")
  # if (file.exists(MMN_summary_file)) {
  #   MMN_summary_sheet <- read.csv(MMN_summary_file)
  #   for (i in 1:nrow(MMN_summary_sheet)) {
  #     MMN_summary_sheet$ID <- x
  #     row <- MMN_summary_sheet[i, , drop = FALSE]
  #     MMN_SME <- rbind(MMN_SME, row)
  #   }
  # } else {
  #   message(paste("MMN file not found for", x))
  # }
}
```

